language: go
services:
  - docker
script:
  - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o httpbasicauth main.go
  - export TAG=$(date "+%Y%m%d%H%M")
  - docker build -t registry.cn-shenzhen.aliyuncs.com/jaywoods/httpbasicauth:${TAG} .
  - docker login --username=${USER} -p ${PASSWORD}  registry.cn-shenzhen.aliyuncs.com
  - docker push registry.cn-shenzhen.aliyuncs.com/jaywoods/httpbasicauth:${TAG}