apiVersion: v1
kind: ServiceAccount
metadata:
  name: http-basic-auth
  namespace: tools
---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: http-basic-auth-role
  namespace: tools
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: http-basic-auth-role-binding
  namespace: tools
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: http-basic-auth-role
subjects:
  - kind: ServiceAccount
    name: http-basic-auth
    namespace: tools
